# Generated by Django 2.1.12 on 2020-01-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktickets', '0002_auto_20200108_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workticket',
            name='pid',
        ),
    ]
