# Generated by Django 2.2.1 on 2019-09-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliUserAccessKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, unique=True, verbose_name='账号标识名称')),
                ('AccessKey_ID', models.CharField(max_length=128, verbose_name='AccessKeyID')),
                ('Access_Key_Secret', models.CharField(max_length=128, verbose_name='Access_KeySecret')),
                ('region_id', models.CharField(max_length=64, verbose_name='地区ID')),
            ],
        ),
    ]
