# Generated by Django 2.1.12 on 2019-09-24 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aliuseraccesskey',
            options={'ordering': ['-c_time'], 'verbose_name': '阿里云认证信息', 'verbose_name_plural': '阿里云认证信息'},
        ),
        migrations.AddField(
            model_name='aliuseraccesskey',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
