# Generated by Django 2.1.12 on 2019-10-05 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0002_auto_20190924_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPlatforms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=64, unique=True, verbose_name='标识名称')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '其他机器信息',
                'verbose_name_plural': '其他机器信息',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='OtherPlatformsHosts',
            fields=[
                ('InstanceId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('InstanceName', models.CharField(max_length=64, verbose_name='主机名称')),
                ('OSType', models.CharField(choices=[('linux', 'linux'), ('windows', 'windows')], default='linux', max_length=12, verbose_name='os类型')),
                ('PublicIpAddress', models.GenericIPAddressField(verbose_name='公网IP')),
                ('PrivateIpAddress', models.GenericIPAddressField(verbose_name='内网IP')),
                ('ZoneId', models.CharField(max_length=128, verbose_name='地区')),
                ('Status', models.CharField(choices=[('运行', '运行'), ('停止', '停止'), ('下线', '下线')], default='运行', max_length=64, verbose_name='状态')),
                ('InstanceNetworkType', models.CharField(max_length=64, verbose_name='网络类型')),
                ('Cpu', models.SmallIntegerField(verbose_name='cpu核数')),
                ('Memory', models.SmallIntegerField(verbose_name='内存大小')),
                ('InstanceChargeType', models.CharField(max_length=64, verbose_name='咋买的啊！？')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '其他机器列表',
                'verbose_name_plural': '其他机器列表',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='otherplatforms',
            name='hosts',
            field=models.ManyToManyField(to='aliecs.OtherPlatformsHosts', verbose_name='主机'),
        ),
    ]
