# Generated by Django 2.1.12 on 2019-10-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0003_auto_20191005_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='Cpu',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='cpu核数'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='InstanceChargeType',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='咋买的啊！？'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='InstanceNetworkType',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='网络类型'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='Memory',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='内存大小'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='PrivateIpAddress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='PublicIpAddress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='ZoneId',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='地区'),
        ),
    ]
