# Generated by Django 2.1.12 on 2019-10-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0004_auto_20191005_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherplatforms',
            name='the_other',
            field=models.BooleanField(default=True),
        ),
    ]
