# Generated by Django 2.1.12 on 2019-10-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0005_otherplatforms_the_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='Cpu',
            field=models.SmallIntegerField(default=1, verbose_name='cpu核数'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='InstanceChargeType',
            field=models.CharField(default='包月', max_length=64, verbose_name='购买或续费方式'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='InstanceNetworkType',
            field=models.CharField(default='', max_length=64, verbose_name='网络类型'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='Memory',
            field=models.SmallIntegerField(default=1, verbose_name='内存大小'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='PrivateIpAddress',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='PublicIpAddress',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='公网IP'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='ZoneId',
            field=models.CharField(default='地球', max_length=128, verbose_name='地区'),
        ),
    ]
