# Generated by Django 2.1.12 on 2019-10-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0006_auto_20191007_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='InstanceNetworkType',
            field=models.CharField(default='集线器', max_length=64, verbose_name='网络类型'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='PrivateIpAddress',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='PublicIpAddress',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='公网IP'),
        ),
    ]
