# Generated by Django 2.1.12 on 2019-10-08 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0007_auto_20191007_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostIpSearchTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=64)),
                ('allip', models.GenericIPAddressField()),
                ('result', models.TextField()),
                ('status', models.SmallIntegerField()),
                ('p_time', models.DateTimeField(auto_now=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
