# Generated by Django 2.1.12 on 2019-11-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0008_hostipsearchtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherplatformshosts',
            name='InternetMaxBandwidthOut',
            field=models.CharField(default='4', max_length=64, verbose_name='出口带宽(Mbps)'),
        ),
        migrations.AlterField(
            model_name='otherplatformshosts',
            name='PrivateIpAddress',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='内网IP'),
        ),
    ]
