# Generated by Django 2.1.12 on 2019-12-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0009_auto_20191130_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostipsearchtask',
            name='instanceame',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='hostipsearchtask',
            name='allip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
