# Generated by Django 2.1.12 on 2019-12-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0011_auto_20191213_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostipsearchtask',
            name='allip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostipsearchtask',
            name='user_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
