# Generated by Django 2.1.12 on 2019-12-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0012_auto_20191219_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostipsearchtask',
            name='result',
            field=models.TextField(null=True),
        ),
    ]
