# Generated by Django 2.1.12 on 2019-12-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0013_auto_20191219_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostipsearchtask',
            name='allname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
