# Generated by Django 2.1.12 on 2019-12-20 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0015_remove_hostipsearchtask_instancename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancenameresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
