# Generated by Django 2.1.12 on 2020-03-04 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aliecs', '0016_auto_20191220_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliuseraccesskey',
            name='project_permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='阿里云主机访问权限'),
        ),
    ]
