# Generated by Django 2.1.12 on 2020-03-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0017_aliuseraccesskey_project_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliuseraccesskey',
            name='project_permissions',
        ),
    ]
