# Generated by Django 2.1.12 on 2020-04-18 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorCpu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('usage_rate', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorDisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('usage', models.CharField(max_length=8)),
                ('free', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorHost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(default='127.0.0.1', verbose_name='被监控端IP')),
                ('hostname', models.CharField(max_length=128, verbose_name='主机名')),
                ('u_date', models.DateTimeField(auto_now=True, verbose_name='上次变动时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('usage', models.CharField(max_length=8)),
                ('free', models.CharField(max_length=8)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.MonitorHost')),
            ],
        ),
        migrations.AddField(
            model_name='monitordisk',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.MonitorHost'),
        ),
        migrations.AddField(
            model_name='monitorcpu',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.MonitorHost'),
        ),
    ]
