# Generated by Django 2.1.12 on 2020-04-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitorhost',
            options={'verbose_name': '监控机器表', 'verbose_name_plural': '监控机器表'},
        ),
    ]
