# Generated by Django 2.1.12 on 2019-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtmcheckdomain',
            name='AccessKey_ID',
            field=models.CharField(default=1234, max_length=128, verbose_name='AccessKeyID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtmcheckdomain',
            name='Access_Key_Secret',
            field=models.CharField(default=12341234, max_length=128, verbose_name='Access_KeySecret'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtmcheckdomain',
            name='gtm_cname',
            field=models.CharField(default=12341234, max_length=64, verbose_name='要解析的gtm_cname地址'),
            preserve_default=False,
        ),
    ]
