# Generated by Django 2.1.12 on 2019-12-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_auto_20191204_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtmcheckdomain',
            name='nick_name',
            field=models.CharField(default=12341, max_length=12, verbose_name='名称标识'),
            preserve_default=False,
        ),
    ]
