# Generated by Django 2.1.12 on 2019-12-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_auto_20191204_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtmcheckdomain',
            name='task_id',
            field=models.TextField(blank=True, null=True, verbose_name='阿里云任务id，不可手动填写'),
        ),
    ]
