# Generated by Django 2.1.12 on 2019-12-23 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_gtmcheckdomain_special_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliRamLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('ali_link', models.TextField(verbose_name='项目阿里云地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '项目阿里云子账号地址',
                'verbose_name_plural': '项目阿里云子账号地址',
            },
        ),
    ]
