# Generated by Django 2.1.12 on 2020-02-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_auto_20200224_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gtmdefaultline',
            options={'verbose_name': '默认线路表', 'verbose_name_plural': '默认线路表'},
        ),
        migrations.AddField(
            model_name='gtmdefaultline',
            name='host_name',
            field=models.CharField(default='gateway', max_length=128, verbose_name='线路名称'),
            preserve_default=False,
        ),
    ]
