# Generated by Django 2.1.12 on 2020-02-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0011_auto_20200224_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtmdefaultline',
            name='Domain',
        ),
        migrations.AddField(
            model_name='gtmcheckdomain',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.GtmDefaultLine'),
        ),
    ]
