# Generated by Django 2.1.12 on 2020-02-24 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_auto_20200224_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtmcheckdomain',
            name='line',
        ),
        migrations.AddField(
            model_name='gtmdefaultline',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.GtmCheckDomain'),
        ),
    ]
