# Generated by Django 2.1.12 on 2020-03-05 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_auto_20200224_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpCytMerchNginx',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hosts_name', models.GenericIPAddressField(verbose_name='cyt商户nginx主机ip地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'cyt商户nginx',
                'verbose_name_plural': 'cyt商户nginx',
            },
        ),
        migrations.CreateModel(
            name='TmpCytWhiteIpTables',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('white_ip', models.GenericIPAddressField(verbose_name='白名单ip')),
                ('result', models.TextField(null=True, verbose_name='结果')),
                ('status', models.SmallIntegerField(default=1, verbose_name='执行状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'cytIP白名单',
                'verbose_name_plural': 'cytIP白名单',
            },
        ),
    ]
