# Generated by Django 2.1.12 on 2020-03-18 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0018_remove_aliuseraccesskey_project_permissions'),
        ('ops', '0014_tmpcytmerchnginx_tmpcytwhiteiptables'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateShadowSocketTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=16, unique=True, verbose_name='模板版本号')),
                ('security_id', models.CharField(max_length=128, verbose_name='vpn安全组id')),
                ('img_id', models.CharField(max_length=128, verbose_name='vpn镜像id')),
                ('secret_key', models.CharField(max_length=128, verbose_name='秘钥对id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ManyToManyField(to='aliecs.AliUserAccessKey', verbose_name='项目选择')),
            ],
            options={
                'verbose_name': 'shadowsocket vpn 创建模板',
                'verbose_name_plural': 'shadowsocket vpn 创建模板',
            },
        ),
    ]
