# Generated by Django 2.1.12 on 2020-03-20 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0018_remove_aliuseraccesskey_project_permissions'),
        ('ops', '0015_createshadowsockettemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createshadowsockettemplate',
            name='project',
        ),
        migrations.AddField(
            model_name='createshadowsockettemplate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aliecs.AliUserAccessKey', verbose_name='项目选择'),
        ),
        migrations.AlterField(
            model_name='createshadowsockettemplate',
            name='secret_key',
            field=models.CharField(max_length=128, verbose_name='秘钥对名称'),
        ),
    ]
