# Generated by Django 2.1.12 on 2020-03-22 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0017_createshadowsockettask'),
    ]

    operations = [
        migrations.AddField(
            model_name='createshadowsockettask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='createshadowsockettemplate',
            name='vswitch_id',
            field=models.CharField(default='vsw-wz9l6y8dttyinlq4cdftv', max_length=128, verbose_name='交换机id'),
            preserve_default=False,
        ),
    ]
