# Generated by Django 2.1.12 on 2020-03-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0018_auto_20200322_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gtmcheckdomain',
            options={'verbose_name': 'CM_GTM域名表', 'verbose_name_plural': 'CM_GTM域名表'},
        ),
        migrations.AlterModelOptions(
            name='gtmdefaultline',
            options={'verbose_name': 'CM_GTM_默认线路表', 'verbose_name_plural': 'CM_GTM_默认线路表'},
        ),
        migrations.AlterModelOptions(
            name='tmpcytmerchnginx',
            options={'verbose_name': 'cyt商户白名单nginx', 'verbose_name_plural': 'cyt商户白名单nginx'},
        ),
    ]
