# Generated by Django 2.1.12 on 2020-03-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0019_auto_20200322_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='createshadowsockettemplate',
            name='vpn_password',
            field=models.CharField(default='2', max_length=128, verbose_name='vpn密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createshadowsockettemplate',
            name='vpn_port',
            field=models.CharField(default='wqerqwer', max_length=12, verbose_name='vpn端口'),
            preserve_default=False,
        ),
    ]
