# Generated by Django 2.1.12 on 2020-03-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0021_createshadowsockettemplate_instancechargetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='createshadowsockettask',
            name='vpn_ip',
            field=models.GenericIPAddressField(default='1.1.1.1'),
            preserve_default=False,
        ),
    ]
