# Generated by Django 2.1.12 on 2020-03-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0022_createshadowsockettask_vpn_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createshadowsockettask',
            name='vpn_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
