# Generated by Django 2.1.12 on 2020-03-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0023_auto_20200322_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createshadowsockettask',
            name='result',
            field=models.TextField(default='0', null=True, verbose_name='结果'),
        ),
    ]
