# Generated by Django 2.1.12 on 2020-03-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0024_auto_20200322_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='createshadowsockettask',
            name='amount',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='createshadowsockettemplate',
            name='admin_security_id',
            field=models.CharField(default='sg-j6c466l9048vk3fajads', max_length=128, verbose_name='需要加白vpnip的admin安全组id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createshadowsockettemplate',
            name='security_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='vpn安全组id'),
        ),
    ]
