# Generated by Django 2.1.12 on 2020-03-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0025_auto_20200324_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createshadowsockettemplate',
            name='admin_security_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='需要加白vpnip的admin安全组id'),
        ),
        migrations.AlterField(
            model_name='createshadowsockettemplate',
            name='security_id',
            field=models.CharField(default='sg-wz9gg9qlfwkxt32j6so7', max_length=128, verbose_name='vpn安全组id'),
            preserve_default=False,
        ),
    ]
