# Generated by Django 2.1.12 on 2020-03-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0026_auto_20200324_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='createshadowsockettask',
            name='_false',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='createshadowsockettask',
            name='vpn_ip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
