# Generated by Django 2.1.12 on 2020-03-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0027_auto_20200325_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createshadowsockettask',
            name='_false',
            field=models.TextField(blank=True, null=True),
        ),
    ]
