# Generated by Django 2.1.12 on 2020-03-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0018_remove_aliuseraccesskey_project_permissions'),
        ('ops', '0028_auto_20200325_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='createshadowsockettemplate',
            name='admmin_security_alikey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_serurity', to='aliecs.AliUserAccessKey', verbose_name='加白的admin安全组对应的阿里云key和地区'),
        ),
        migrations.AlterField(
            model_name='createshadowsockettemplate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='aliecs.AliUserAccessKey', verbose_name='项目选择'),
        ),
    ]
