# Generated by Django 2.1.12 on 2020-03-29 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0018_remove_aliuseraccesskey_project_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0029_auto_20200325_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateForwardTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(default=1)),
                ('amount', models.SmallIntegerField(default=1)),
                ('vpn_ip', models.TextField(blank=True, null=True)),
                ('_false', models.TextField(blank=True, null=True)),
                ('result', models.TextField(default='0', null=True, verbose_name='结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='CreateForwardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=16, unique=True, verbose_name='模板版本号')),
                ('security_id', models.CharField(max_length=128, verbose_name='vpn安全组id')),
                ('img_id', models.CharField(max_length=128, verbose_name='vpn镜像id')),
                ('secret_key', models.CharField(max_length=128, verbose_name='秘钥对名称')),
                ('vswitch_id', models.CharField(max_length=128, verbose_name='交换机id')),
                ('vpn_port', models.CharField(max_length=12, verbose_name='vpn端口')),
                ('vpn_password', models.CharField(max_length=128, verbose_name='vpn密码')),
                ('InstanceChargeType', models.CharField(choices=[('PrePaid', '包年包月'), ('PostPaid', '按量付费')], default='PostPaid', max_length=24, verbose_name='机器付费方式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwardproject', to='aliecs.AliUserAccessKey', verbose_name='项目选择')),
            ],
        ),
        migrations.AlterField(
            model_name='createshadowsockettemplate',
            name='admin_security_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='需要加白vpnIP的admin安全组id'),
        ),
        migrations.AlterField(
            model_name='createshadowsockettemplate',
            name='admmin_security_alikey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_serurity', to='aliecs.AliUserAccessKey', verbose_name='需要加白vpnIP的admin安全组对应的阿里云key和地区'),
        ),
        migrations.AlterField(
            model_name='createshadowsockettemplate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadowsocketproject', to='aliecs.AliUserAccessKey', verbose_name='项目选择'),
        ),
        migrations.AddField(
            model_name='createforwardtask',
            name='forward_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.CreateForwardTemplate'),
        ),
        migrations.AddField(
            model_name='createforwardtask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
