# Generated by Django 2.1.12 on 2020-03-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0030_auto_20200329_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createforwardtask',
            old_name='vpn_ip',
            new_name='forward_iip',
        ),
        migrations.RemoveField(
            model_name='createforwardtemplate',
            name='vpn_password',
        ),
        migrations.RemoveField(
            model_name='createforwardtemplate',
            name='vpn_port',
        ),
        migrations.AddField(
            model_name='createforwardtask',
            name='forward_pip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createforwardtemplate',
            name='forward_port',
            field=models.CharField(default='1234', max_length=12, verbose_name='squid端口'),
            preserve_default=False,
        ),
    ]
