# Generated by Django 2.1.12 on 2020-04-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0031_auto_20200329_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createforwardtemplate',
            options={'verbose_name': 'forward 创建模板', 'verbose_name_plural': 'forward 创建模板'},
        ),
        migrations.AlterField(
            model_name='createforwardtemplate',
            name='img_id',
            field=models.CharField(max_length=128, verbose_name='forward镜像id'),
        ),
        migrations.AlterField(
            model_name='createforwardtemplate',
            name='security_id',
            field=models.CharField(max_length=128, verbose_name='forward安全组id'),
        ),
    ]
