# Generated by Django 2.1.12 on 2019-12-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gtm_permission',
            field=models.BooleanField(default=True, verbose_name='此用户是否允许访问gtm切换'),
        ),
        migrations.AddField(
            model_name='user',
            name='hosts_permission',
            field=models.BooleanField(default=True, verbose_name='此用户是否允许访问主机相关'),
        ),
    ]
