# Generated by Django 2.1.12 on 2020-03-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0018_remove_aliuseraccesskey_project_permissions'),
        ('user', '0003_auto_20191219_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aliecs.AliUserAccessKey', verbose_name='阿里云主机访问权限'),
        ),
    ]
