# Generated by Django 2.1.12 on 2020-03-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_project_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
