# Generated by Django 2.1.12 on 2020-03-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliecs', '0018_remove_aliuseraccesskey_project_permissions'),
        ('user', '0005_remove_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='project_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='project_permissions',
            field=models.ManyToManyField(blank=True, null=True, to='aliecs.AliUserAccessKey', verbose_name='阿里云主机访问权限'),
        ),
    ]
