# Generated by Django 2.1.12 on 2020-03-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200304_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cyt_iptables_permission',
            field=models.BooleanField(default=True, verbose_name='此用户是否允许访问cyt商户加白'),
        ),
    ]
