# Generated by Django 2.1.12 on 2020-03-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_create_shadowsocket_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='worktickets_permission',
            field=models.BooleanField(default=True, verbose_name='此用户是否允许访问工单'),
        ),
    ]
