# Generated by Django 2.1.12 on 2020-04-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_worktickets_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_forward_permission',
            field=models.BooleanField(default=True, verbose_name='此用户是否允许创建forward'),
        ),
    ]
