# Generated by Django 2.1.12 on 2020-04-29 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200429_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiongroup',
            name='user',
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
