# Generated by Django 2.1.12 on 2020-04-29 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200429_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
