# Generated by Django 2.1.12 on 2020-01-08 07:13

from django.db import migrations, models
import tools.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='上传用户')),
                ('file', models.FileField(blank=True, upload_to=tools.storage.PathAndRename('./'), verbose_name='上传文件')),
                ('archive', models.CharField(blank=True, default='其他', max_length=201, null=True, verbose_name='文件归档')),
                ('filename', models.CharField(blank=True, max_length=201, null=True, verbose_name='文件名')),
                ('filepath', models.CharField(blank=True, max_length=201, null=True, verbose_name='文件路径')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件类型')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='文件大小')),
                ('create_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='文件日期')),
            ],
            options={
                'verbose_name': '文件上传',
                'verbose_name_plural': '文件上传',
            },
        ),
    ]
