# Generated by Django 2.1.12 on 2020-01-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, upload_to='../../tmp', verbose_name='上传文件'),
        ),
    ]
